import type { Metadata } from "next";
import "./globals.css";
import { mulish } from "./fonts";
import Header from "./components/modules/header";
import MobileBottomNav from "./components/modules/header/mobile/MobileBottomNav";
import MobileMenuSlide from "./components/modules/header/mobile/MobileMenuSlide";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className={`${mulish.className} antialiased flex-row`}>
        {children}
      </main>
      <MobileMenuSlide />
      <MobileBottomNav />
    </div>
  );
}
